default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: make-check
        name: make check
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit
      - id: make-update-devserver
        name: make update-devserver
        entry: make update-devserver
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - post-commit
      - id: make-test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
