# Generated by Django 6.0.5 on 2026-06-09 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djangoapp.user_interface.models


def create_initial_user_profiles(apps, schema_editor):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    user_profile_model = apps.get_model("user_interface", "UserProfile")
    for user in user_model.objects.all().iterator():
        user_profile_model.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-detect browser language"),
                            ("en", "English"),
                            ("de", "German"),
                        ],
                        default="auto",
                        help_text="Choose auto-detection or force one of the configured application languages.",
                        max_length=16,
                    ),
                ),
                (
                    "avatar_type",
                    models.CharField(
                        choices=[("initials", "Initials"), ("image", "Uploaded image")],
                        default="initials",
                        help_text="Use either generated initials or an uploaded image across the user interface.",
                        max_length=16,
                    ),
                ),
                (
                    "avatar_image",
                    models.FileField(
                        blank=True,
                        help_text="Optional image shown when uploaded image mode is selected.",
                        upload_to=djangoapp.user_interface.models.user_profile_avatar_upload_to,
                    ),
                ),
                (
                    "avatar_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional short label used instead of generated initials.",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
            },
        ),
        migrations.RunPython(create_initial_user_profiles, migrations.RunPython.noop),
    ]
