# Generated by Django 6.0.5 on 2026-06-09 07:47

from django.conf import settings
from django.db import migrations, models


def set_default_language_for_legacy_profiles(apps, schema_editor):
    user_profile_model = apps.get_model("user_interface", "UserProfile")
    user_profile_model.objects.filter(language_preference="auto").update(language_preference=settings.LANGUAGE_CODE)


class Migration(migrations.Migration):
    dependencies = [
        ("user_interface", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_default_language_for_legacy_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="en",
                help_text="Choose one of the configured application languages.",
                max_length=16,
            ),
        ),
    ]
