# Generated by Django 6.0.5 on 2026-06-09 09:41

import djangoapp.user_interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_interface", "0002_alter_userprofile_language_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_label",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_type",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_system_user",
            field=models.BooleanField(
                default=False,
                help_text="Use the system-agent avatar when no custom avatar image is uploaded.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_image",
            field=models.FileField(
                blank=True,
                help_text="Optional avatar image shown everywhere the user appears.",
                upload_to=djangoapp.user_interface.models.user_profile_avatar_upload_to,
            ),
        ),
    ]
