# Generated by Django 6.0.5 on 2026-06-09 09:54

from django.db import migrations, models


def set_avatar_type_defaults(apps, schema_editor):
    UserProfile = apps.get_model("user_interface", "UserProfile")

    UserProfile.objects.filter(is_system_user=True).update(avatar_type="image")
    UserProfile.objects.exclude(avatar_image="").update(avatar_type="image")


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("user_interface", "0003_remove_userprofile_avatar_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_type",
            field=models.CharField(
                choices=[("initials", "Initials"), ("image", "Uploaded image")],
                default="initials",
                help_text="Choose whether the profile should render initials or an image by default.",
                max_length=16,
            ),
        ),
        migrations.RunPython(set_avatar_type_defaults, noop_reverse),
    ]
