"""
Django settings for djangoapp project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default):
    value = os.environ.get(name)

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    value = os.environ.get(name)

    if value is None:
        return default

    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-^d!g3oga6mmxg&&6)if8+2s-^6u7_etn-(3&3g4h3-z+yo*iwu",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

DEFAULT_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

PRODUCT_DISPLAY_NAME = os.environ.get("PRODUCT_DISPLAY_NAME", "Ticket System Mock")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ["*"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cotton",
    "djangoapp.branding",
    "djangoapp.core",
    "djangoapp.healthchecks",
    "djangoapp.rest_api",
    "djangoapp.user_interface",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "djangoapp.branding.context_processors.app_branding",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "itoticketing"),
        "USER": os.environ.get("POSTGRES_USER", "itoticketing"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "PlsChgMePostgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "database"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://:%s@%s:%s/%s"
        % (
            os.environ.get("CACHE_PASSWORD", "PlsChgMeCache"),
            os.environ.get("CACHE_HOST", "cache"),
            os.environ.get("CACHE_PORT", "6379"),
            os.environ.get("CACHE_DB", "0"),
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

BASE_AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_PASSWORD_VALIDATORS = [] if DEBUG else BASE_AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", _("English")),
    ("de", _("German")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True

DJANGO_LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", DEFAULT_LOG_LEVEL).upper()

DJANGO_RUNTIME_ROOT = Path(os.environ.get("DJANGO_RUNTIME_ROOT", str(BASE_DIR / "runtime")))
DJANGO_STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", str(DJANGO_RUNTIME_ROOT / "static")))
DJANGO_MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", str(DJANGO_RUNTIME_ROOT / "media")))
DJANGO_CERT_ROOT = Path(os.environ.get("DJANGO_CERT_ROOT", str(DJANGO_RUNTIME_ROOT / "certificates")))
DJANGO_PROVISIONING_DIR = Path(os.environ.get("DJANGO_PROVISIONING_DIR", str(DJANGO_RUNTIME_ROOT / "provisioning")))
DJANGO_PROVISIONING_FLAG = Path(
    os.environ.get(
        "DJANGO_PROVISIONING_FLAG",
        str(DJANGO_PROVISIONING_DIR / "fixtures-loaded.flag"),
    )
)
DJANGO_BOOTSTRAP_FIXTURES = env_list("DJANGO_BOOTSTRAP_FIXTURES", ["initial_data"])
DJANGO_STATIC_FIXTURES = env_list("DJANGO_STATIC_FIXTURES", ["static_data"])


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = str(DJANGO_STATIC_ROOT)
STATICFILES_DIRS = [BASE_DIR / "static"]

SERVICE_BASE_URL = os.environ.get("SERVICE_BASE_URL", "http://localhost")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [SERVICE_BASE_URL])
MEDIA_URL = "/media/"
MEDIA_ROOT = str(DJANGO_MEDIA_ROOT)

FIXTURE_DIRS = [str(BASE_DIR / "fixtures")]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
