# Generated by Django 6.0.5 on 2026-06-04 16:51

from django.db import migrations, models


def backfill_board_positions(apps, schema_editor):
    issue_model = apps.get_model("core", "Issue")

    workflow_states = [
        "BACKLOG",
        "NEW",
        "TRIAGE",
        "ASSIGNED",
        "IN_PROGRESS",
        "WAITING",
        "RESOLVED",
        "CLOSED",
        "REJECTED",
        "DUPLICATE",
    ]
    priorities = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

    for workflow_state in workflow_states:
        for priority in priorities:
            queryset = issue_model.objects.filter(
                workflow_state=workflow_state,
                priority=priority,
            ).order_by("created_at", "pk")
            for index, issue in enumerate(queryset, start=1):
                issue_model.objects.filter(pk=issue.pk).update(board_position=index)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_collection_issue_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="board_position",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_board_positions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issue",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("DUPLICATE", "Duplicate"),
                ],
                default="BACKLOG",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="from_state",
            field=models.CharField(
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("DUPLICATE", "Duplicate"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("DUPLICATE", "Duplicate"),
                ],
                max_length=24,
            ),
        ),
    ]
