# Generated by Django 6.0.5 on 2026-06-05 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_draftissueattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("target_url", models.URLField()),
                ("enabled", models.BooleanField(default=True)),
                ("subscribed_event_types", models.JSONField(blank=True, default=list)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("timeout_seconds", models.PositiveIntegerField(default=5)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_backoff_seconds", models.PositiveIntegerField(default=60)),
                (
                    "last_delivery_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("partial_failure", "Partial failure"),
                            ("failed", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "last_delivery_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("issue.created", "Issue created"),
                            ("issue.updated", "Issue updated"),
                            ("issue.queue_assigned", "Issue queue assigned"),
                            ("issue.commented", "Issue commented"),
                            ("issue.closed", "Issue closed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("partial_failure", "Partial failure"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_body", models.TextField(blank=True)),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "webhook_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="core.webhookendpoint",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="core.webhookevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("webhook_endpoint", "webhook_event", "attempt_number"),
                        name="core_webhook_attempt_unique_number",
                    )
                ],
            },
        ),
    ]
