# Generated by Django 6.0.5 on 2026-06-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_webhookendpoint_webhookevent_webhookdeliveryattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="target_endpoint_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
