# Generated by Django 6.0.5 on 2026-06-07 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_webhookevent_target_endpoint_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FIELD_CHANGED", "Field changed"),
                            ("ATTACHMENT_ADDED", "Attachment added"),
                            ("ATTACHMENT_UPDATED", "Attachment updated"),
                            ("ATTACHMENT_REMOVED", "Attachment removed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=32)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_history_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_events",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-pk"],
            },
        ),
    ]
