# Generated by Django 6.0.5 on 2026-06-12 21:46

import djangoapp.core.models.webhook_endpoint
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_issuehistoryevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookendpoint",
            name="target_url",
            field=models.CharField(
                max_length=200,
                validators=[
                    djangoapp.core.models.webhook_endpoint.validate_webhook_target_url
                ],
            ),
        ),
    ]
