# Generated by Django 6.0.5 on 2026-06-12 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0008_alter_webhookendpoint_target_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStateAutoAssignmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("BACKLOG", "Backlog"),
                            ("NEW", "New"),
                            ("TRIAGE", "Triage"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING", "Waiting"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REJECTED", "Rejected"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_state_auto_assignment_rules",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_state_auto_assignment_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow state auto-assignment rule",
                "verbose_name_plural": "Workflow state auto-assignment rules",
                "ordering": ["workflow_state"],
            },
        ),
    ]
