# Generated by Django 6.0.5 on 2026-06-12

from django.db import migrations, models

WORKFLOW_STATE_CHOICES = [
    ("NEW", "New"),
    ("TRIAGE", "Triage"),
    ("ASSIGNED", "Assigned"),
    ("IN_PROGRESS", "In Progress"),
    ("WAITING", "Waiting"),
    ("RESOLVED", "Resolved"),
    ("CLOSED", "Closed"),
    ("REJECTED", "Rejected"),
    ("DUPLICATE", "Duplicate"),
]


def remap_backlog_to_new(apps, schema_editor):
    issue_model = apps.get_model("core", "Issue")
    transition_model = apps.get_model("core", "IssueStateTransition")
    rule_model = apps.get_model("core", "WorkflowStateAutoAssignmentRule")

    issue_model.objects.filter(workflow_state="BACKLOG").update(workflow_state="NEW")
    transition_model.objects.filter(from_state="BACKLOG").update(from_state="NEW")
    transition_model.objects.filter(to_state="BACKLOG").update(to_state="NEW")

    if rule_model.objects.filter(workflow_state="NEW").exists():
        rule_model.objects.filter(workflow_state="BACKLOG").delete()
    else:
        rule_model.objects.filter(workflow_state="BACKLOG").update(workflow_state="NEW")

    _normalize_new_board_positions(issue_model)


def _normalize_new_board_positions(issue_model):
    priorities = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    for priority in priorities:
        queryset = issue_model.objects.filter(
            archived_at__isnull=True,
            workflow_state="NEW",
            priority=priority,
        ).order_by("board_position", "created_at", "pk")
        for index, issue in enumerate(queryset, start=1):
            issue_model.objects.filter(pk=issue.pk).update(board_position=index)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_workflowstateautoassignmentrule"),
    ]

    operations = [
        migrations.RunPython(remap_backlog_to_new, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issue",
            name="workflow_state",
            field=models.CharField(
                choices=WORKFLOW_STATE_CHOICES,
                default="NEW",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="from_state",
            field=models.CharField(
                choices=WORKFLOW_STATE_CHOICES,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="to_state",
            field=models.CharField(
                choices=WORKFLOW_STATE_CHOICES,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstateautoassignmentrule",
            name="workflow_state",
            field=models.CharField(
                choices=WORKFLOW_STATE_CHOICES,
                max_length=24,
                unique=True,
            ),
        ),
    ]
