# Generated by Django 6.0.5 on 2026-06-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_backlog_workflow_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueDescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description_markdown", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit this template to one issue category.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_description_templates",
                        to="core.issuecategory",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit this template to one collection.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_description_templates",
                        to="core.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue description template",
                "verbose_name_plural": "Issue description templates",
                "ordering": ["name"],
            },
        ),
    ]
