# Generated by Django 6.0.5 on 2026-06-12 23:23

from django.db import migrations, models


def remap_duplicate_to_rejected(apps, schema_editor):
    issue_model = apps.get_model("core", "Issue")
    transition_model = apps.get_model("core", "IssueStateTransition")
    rule_model = apps.get_model("core", "WorkflowStateAutoAssignmentRule")

    issue_model.objects.filter(workflow_state="DUPLICATE").update(workflow_state="REJECTED")
    transition_model.objects.filter(from_state="DUPLICATE").update(from_state="REJECTED")
    transition_model.objects.filter(to_state="DUPLICATE").update(to_state="REJECTED")

    if rule_model.objects.filter(workflow_state="REJECTED").exists():
        rule_model.objects.filter(workflow_state="DUPLICATE").delete()
    else:
        rule_model.objects.filter(workflow_state="DUPLICATE").update(workflow_state="REJECTED")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_issuedescriptiontemplate"),
    ]

    operations = [
        migrations.RunPython(remap_duplicate_to_rejected, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issue",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="from_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatetransition",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstateautoassignmentrule",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("TRIAGE", "Triage"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("WAITING", "Waiting"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
    ]
