# Generated by Django 6.0.5 on 2026-06-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0012_alter_issue_workflow_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_details",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
