# Generated by Django 6.0.5 on 2026-06-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_groupdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="core.issuecategory",
            ),
        ),
    ]
