# Generated by Django 6.0.5 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_issue_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="disable_ssl_certificate_validation",
            field=models.BooleanField(
                default=False,
                help_text="Use only for trusted endpoints with self-signed or otherwise invalid HTTPS certificates.",
                verbose_name="Disable SSL certificate validation",
            ),
        ),
    ]
