# Generated by Django 6.0.5 on 2026-06-05 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appbranding",
            name="dark_primary_color",
            field=models.CharField(
                default="#01aaff",
                help_text="Primary accent color for dark mode.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color in the format #RRGGBB.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="appbranding",
            name="dark_primary_hover_color",
            field=models.CharField(
                default="#79c0ff",
                help_text="Primary hover accent color for dark mode.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color in the format #RRGGBB.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="appbranding",
            name="light_primary_color",
            field=models.CharField(
                default="#0172ad",
                help_text="Primary accent color for light mode.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color in the format #RRGGBB.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="appbranding",
            name="light_primary_hover_color",
            field=models.CharField(
                default="#015887",
                help_text="Primary hover accent color for light mode.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color in the format #RRGGBB.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
