# Generated by Django 6.0.5 on 2026-06-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0002_appbranding_dark_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appbranding",
            name="login_message_level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                help_text="Visual style for the login screen message.",
                max_length=20,
                verbose_name="Login message style",
            ),
        ),
        migrations.AddField(
            model_name="appbranding",
            name="login_message_text",
            field=models.TextField(
                blank=True,
                help_text="Optional message shown above the sign-in form.",
                verbose_name="Login screen message",
            ),
        ),
    ]
