#!/bin/bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${REPO_ROOT:-$(cd "$script_dir/.." && pwd)}"

bundle_zip="${BUNDLE_ZIP:-$repo_root/build/deploy/ticket-system-mock-test-bundle.zip}"
staging_root="${STAGING_ROOT:-$repo_root/.tms-prod-test}"
host_name="${HOST_NAME:-localhost}"
http_port="${HTTP_PORT:-8080}"
https_port="${HTTPS_PORT:-8443}"
bundle_name="$(basename "$bundle_zip" .zip)"
deployment_dir="$staging_root/$bundle_name"
service_base_url="${SERVICE_BASE_URL:-https://$host_name:$https_port}"
webapp_image="${WEBAPP_IMAGE:-}"

is_local_only_image_reference() {
    local image_ref="$1"

    [[ "$image_ref" == localhost.local/* ]]
}

require_command() {
    local command_name="$1"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "required command not found: $command_name" >&2
        exit 1
    fi
}

random_hex() {
    local byte_count="$1"
    openssl rand -hex "$byte_count"
}

compose() {
    (
        cd "$deployment_dir"
        set -a
        . ./.env
        set +a
        env -u COMPOSE_PROJECT_NAME docker compose \
            -f docker-compose.yaml \
            -f docker-compose.override.yaml \
            "$@"
    )
}

verify_management_completion() {
    local management_status

    management_status="$(compose ps -a --format json | grep '"Service":"management"' || true)"

    if [[ -z "$management_status" ]]; then
        echo "management container status not found" >&2
        exit 1
    fi

    if [[ "$management_status" == *'"State":"running"'* && "$management_status" == *'"Health":"healthy"'* ]]; then
        return 0
    fi

    if [[ "$management_status" != *'"State":"exited"'* || "$management_status" != *'"ExitCode":0'* ]]; then
        echo "management bootstrap did not complete successfully" >&2
        compose logs --no-color management >&2
        exit 1
    fi
}

write_env_file() {
    local resolved_webapp_image="$1"
    local django_secret_key="$2"
    local postgres_password="$3"
    local cache_password="$4"

    cat >"$deployment_dir/.env" <<EOF
# Generated by scripts/setup_production_test_instance.bash
WEBAPP_IMAGE=$resolved_webapp_image
DJANGO_SECRET_KEY=$django_secret_key
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
DJANGO_TIME_ZONE=UTC
SERVICE_BASE_URL=$service_base_url
DJANGO_CSRF_TRUSTED_ORIGINS=$service_base_url
POSTGRES_DB=ticket_system_mock
POSTGRES_USER=ticket_system_mock
POSTGRES_PASSWORD=$postgres_password
CACHE_PASSWORD=$cache_password
NGINX_SERVER_NAME=$host_name
NGINX_HTTP_PORT=$http_port
NGINX_HTTPS_PORT=$https_port
EOF
}

stage_bundle() {
    rm -rf "$staging_root"
    mkdir -p "$staging_root"
    cp "$bundle_zip" "$staging_root/"

    (
        cd "$staging_root"
        unzip -oq "$(basename "$bundle_zip")"
    )
}

resolve_webapp_image() {
    local metadata_file="$deployment_dir/build-metadata.env"
    local metadata_image

    if [[ -f "$metadata_file" ]]; then
        metadata_image="$(grep '^WEBAPP_IMAGE=' "$metadata_file" | head -n 1 | cut -d'=' -f2-)"

        if [[ -n "$metadata_image" ]]; then
            printf '%s\n' "$metadata_image"
            return 0
        fi
    fi

    if [[ -n "$webapp_image" ]]; then
        printf '%s\n' "$webapp_image"
        return 0
    fi

    printf '%s\n' 'hoelsner/ticket-system-mock:latest'
}

pull_images() {
    local resolved_webapp_image="$1"

    if is_local_only_image_reference "$resolved_webapp_image"; then
        echo "skipping webapp image pull for local-only image $resolved_webapp_image"
        compose pull database cache nginx
        return 0
    fi

    compose pull
}

verify_https_redirect() {
    local header_file
    local normalized_headers
    header_file="$(mktemp)"
    normalized_headers="$(mktemp)"

    curl -k -sS -I "$service_base_url/" >"$header_file"
    tr -d '\r' <"$header_file" >"$normalized_headers"

    if ! grep -q '^HTTP/.* 302' "$normalized_headers"; then
        echo "expected a redirect response from $service_base_url/" >&2
        cat "$normalized_headers" >&2
        rm -f "$header_file" "$normalized_headers"
        exit 1
    fi

    if ! grep -q '^Location: /accounts/login/?next=/$' "$normalized_headers"; then
        echo "expected redirect to the login page from $service_base_url/" >&2
        cat "$normalized_headers" >&2
        rm -f "$header_file" "$normalized_headers"
        exit 1
    fi

    rm -f "$header_file" "$normalized_headers"
}

verify_admin_login() {
    local temp_dir
    local csrf_token

    temp_dir="$(mktemp -d)"
    trap 'rm -rf "$temp_dir"' RETURN

    curl -k -sS -c "$temp_dir/cookies.txt" \
        "$service_base_url/accounts/login/?next=/" >"$temp_dir/login.html"

    csrf_token="$(grep -o 'name="csrfmiddlewaretoken" value="[^"]*"' "$temp_dir/login.html" | sed 's/.*value="//; s/"$//' | head -n 1)"

    if [[ -z "$csrf_token" ]]; then
        echo "failed to extract CSRF token from the login page" >&2
        exit 1
    fi

    curl -k -sS -b "$temp_dir/cookies.txt" \
        -c "$temp_dir/cookies.txt" \
        -e "$service_base_url/accounts/login/?next=/" \
        -H "Origin: $service_base_url" \
        -X POST "$service_base_url/accounts/login/?next=/" \
        --data-urlencode "csrfmiddlewaretoken=$csrf_token" \
        --data-urlencode 'username=admin' \
        --data-urlencode 'password=admin1234' \
        --data-urlencode 'next=/' >"$temp_dir/post_login_headers.txt"

    curl -k -sS -b "$temp_dir/cookies.txt" \
        "$service_base_url/" >"$temp_dir/home.html"

    if ! grep -Eq 'Signed in successfully\.|Sign out' "$temp_dir/home.html"; then
        echo "admin login verification failed for $service_base_url" >&2
        exit 1
    fi

    rm -rf "$temp_dir"
    trap - RETURN
}

main() {
    local resolved_webapp_image

    require_command curl
    require_command docker
    require_command openssl
    require_command unzip

    if [[ ! -f "$bundle_zip" ]]; then
        echo "deployment bundle ZIP not found: $bundle_zip" >&2
        exit 1
    fi

    echo "staging deployment bundle from $bundle_zip"
    stage_bundle

    resolved_webapp_image="$(resolve_webapp_image)"

    echo "writing deployment overrides in $deployment_dir"
    write_env_file "$resolved_webapp_image" "$(random_hex 32)" "$(random_hex 24)" "$(random_hex 24)"

    echo "pulling container images"
    pull_images "$resolved_webapp_image"

    echo "resetting any existing stack state"
    compose down -v >/dev/null 2>&1 || true

    echo "starting production test stack"
    compose up -d

    echo "verifying management bootstrap completion"
    verify_management_completion

    echo "checking service status"
    compose ps

    echo "verifying HTTPS entrypoint on $service_base_url"
    verify_https_redirect

    echo "verifying admin login"
    verify_admin_login

    echo "production test instance is ready at $service_base_url"
    echo "deployment directory: $deployment_dir"
    echo "admin credentials: admin / admin1234"
}

main "$@"