#!/bin/bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${REPO_ROOT:-$(cd "$script_dir/.." && pwd)}"

bundle_zip="${BUNDLE_ZIP:-$repo_root/build/deploy/itoperation-ticketing-demo-service-test-bundle.zip}"
staging_root="${STAGING_ROOT:-$repo_root/.tms-prod-test}"
host_name="${HOST_NAME:-localhost}"
http_port="${HTTP_PORT:-8080}"
https_port="${HTTPS_PORT:-8443}"
bundle_name="$(basename "$bundle_zip" .zip)"
deployment_dir="$staging_root/$bundle_name"
service_base_url="${SERVICE_BASE_URL:-https://$host_name:$https_port}"

require_command() {
    local command_name="$1"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "required command not found: $command_name" >&2
        exit 1
    fi
}

random_hex() {
    local byte_count="$1"
    openssl rand -hex "$byte_count"
}

compose() {
    (
        cd "$deployment_dir"
        set -a
        . ./.env
        set +a
        env -u COMPOSE_PROJECT_NAME docker compose \
            -f docker-compose.yaml \
            -f docker-compose.override.yaml \
            "$@"
    )
}

verify_management_completion() {
    local management_status

    management_status="$(compose ps -a --format json | grep '"Service":"management"' || true)"

    if [[ -z "$management_status" ]]; then
        echo "management container status not found" >&2
        exit 1
    fi

    if [[ "$management_status" != *'"State":"exited"'* || "$management_status" != *'"ExitCode":0'* ]]; then
        echo "management bootstrap did not complete successfully" >&2
        compose logs --no-color management >&2
        exit 1
    fi
}

write_env_file() {
    local django_secret_key="$1"
    local postgres_password="$2"
    local cache_password="$3"

    cat >"$deployment_dir/.env" <<EOF
# Generated by scripts/setup_production_test_instance.bash
WEBAPP_IMAGE=hoelsner/ticket-system-mock:latest
DJANGO_SECRET_KEY=$django_secret_key
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
DJANGO_TIME_ZONE=UTC
SERVICE_BASE_URL=$service_base_url
POSTGRES_DB=itoticketing
POSTGRES_USER=itoticketing
POSTGRES_PASSWORD=$postgres_password
CACHE_PASSWORD=$cache_password
NGINX_SERVER_NAME=$host_name
NGINX_HTTP_PORT=$http_port
NGINX_HTTPS_PORT=$https_port
EOF
}

write_override_file() {
    cat >"$deployment_dir/docker-compose.override.yaml" <<'EOF'
services:
  management:
    volumes:
      - ./run_management_fixed.bash:/app/deploy/containers/webapp/run_management.bash:ro
EOF
}

write_management_script() {
    cat >"$deployment_dir/run_management_fixed.bash" <<'EOF'
#!/bin/bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"

webapp_dir="${WEBAPP_DIR:-$repo_root/src/webapp}"
runtime_root="${DJANGO_RUNTIME_ROOT:-$repo_root/runtime}"
static_root="${DJANGO_STATIC_ROOT:-$runtime_root/static}"
media_root="${DJANGO_MEDIA_ROOT:-$runtime_root/media}"
cert_root="${DJANGO_CERT_ROOT:-$runtime_root/certificates}"
nginx_config_dir="${NGINX_CONFIG_DIR:-$runtime_root/nginx}"
nginx_config_file="${NGINX_CONFIG_FILE:-$nginx_config_dir/default.conf}"
provisioning_dir="${DJANGO_PROVISIONING_DIR:-$runtime_root/provisioning}"
provisioning_flag="${DJANGO_PROVISIONING_FLAG:-$provisioning_dir/fixtures-loaded.flag}"
python_bin="${PYTHON_BIN:-$webapp_dir/.venv/bin/python3}"
nginx_server_name="${NGINX_SERVER_NAME:-_}"
nginx_client_max_body_size="${NGINX_CLIENT_MAX_BODY_SIZE:-10m}"

if [[ ! -x "$python_bin" ]]; then
    python_bin="${PYTHON_BIN_FALLBACK:-python3}"
fi

if [[ ! -d "$webapp_dir" ]]; then
    echo "webapp directory not found at $webapp_dir"
    exit 1
fi

cd "$webapp_dir" || exit 1

mkdir -p "$static_root" "$media_root" "$cert_root" "$nginx_config_dir" "$provisioning_dir"

export DJANGO_STATIC_ROOT="$static_root"
export DJANGO_MEDIA_ROOT="$media_root"

run_manage() {
    "$python_bin" manage.py "$@"
}

generate_self_signed_certificate() {
    local service_name="$1"
    local certificate_file="$cert_root/${service_name}.crt"
    local private_key_file="$cert_root/${service_name}.key"

    if [[ -f "$certificate_file" && -f "$private_key_file" ]]; then
        echo "$service_name certificate already exists, skipping generation"
        return 0
    fi

    if ! command -v openssl >/dev/null 2>&1; then
        echo "openssl is required to generate the $service_name self-signed certificate"
        exit 1
    fi

    echo "generating self-signed certificate for $service_name"
    openssl req \
        -x509 \
        -nodes \
        -newkey rsa:2048 \
        -keyout "$private_key_file" \
        -out "$certificate_file" \
        -days 3650 \
        -subj "/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
    chmod 600 "$private_key_file"
    chmod 644 "$certificate_file"
}

generate_nginx_configuration() {
    echo "writing nginx configuration to $nginx_config_file"
    cat >"$nginx_config_file" <<NGINXCONF
upstream django_upstream {
    server webapp:8000;
}

server {
    listen 80;
    server_name $nginx_server_name;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name $nginx_server_name;
    client_max_body_size $nginx_client_max_body_size;
    ssl_certificate $cert_root/nginx.crt;
    ssl_certificate_key $cert_root/nginx.key;

    location /static/ {
        alias $static_root/;
        access_log off;
        expires 1h;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias $media_root/;
        access_log off;
        expires 1h;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://django_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
NGINXCONF
}

ensure_admin_user() {
    echo "ensuring admin user exists"
    run_manage shell -c '
from django.contrib.auth import get_user_model

User = get_user_model()
user, _created = User.objects.get_or_create(username="admin")
user.first_name = "Admin"
user.last_name = "User"
user.is_active = True
user.is_staff = True
user.is_superuser = True
user.set_password("admin1234")
user.save()
'
}

echo "running database migrations"
run_manage migrate --noinput

generate_self_signed_certificate "gunicorn"
generate_self_signed_certificate "nginx"
generate_nginx_configuration

ensure_admin_user

touch "$provisioning_flag"
echo "wrote provisioning flag to $provisioning_flag"

echo "collecting static files into $static_root"
run_manage collectstatic --noinput

echo "prepared shared runtime volume under $runtime_root"
EOF
}

stage_bundle() {
    rm -rf "$staging_root"
    mkdir -p "$staging_root"
    cp "$bundle_zip" "$staging_root/"

    (
        cd "$staging_root"
        unzip -oq "$(basename "$bundle_zip")"
    )
}

verify_https_redirect() {
    local header_file
    local normalized_headers
    header_file="$(mktemp)"
    normalized_headers="$(mktemp)"

    curl -k -sS -I "$service_base_url/" >"$header_file"
    tr -d '\r' <"$header_file" >"$normalized_headers"

    if ! grep -q '^HTTP/.* 302' "$normalized_headers"; then
        echo "expected a redirect response from $service_base_url/" >&2
        cat "$normalized_headers" >&2
        rm -f "$header_file" "$normalized_headers"
        exit 1
    fi

    if ! grep -q '^Location: /accounts/login/?next=/$' "$normalized_headers"; then
        echo "expected redirect to the login page from $service_base_url/" >&2
        cat "$normalized_headers" >&2
        rm -f "$header_file" "$normalized_headers"
        exit 1
    fi

    rm -f "$header_file" "$normalized_headers"
}

verify_admin_login() {
    local temp_dir
    local csrf_token

    temp_dir="$(mktemp -d)"
    trap 'rm -rf "$temp_dir"' RETURN

    curl -k -sS -c "$temp_dir/cookies.txt" \
        "$service_base_url/accounts/login/?next=/" >"$temp_dir/login.html"

    csrf_token="$(grep -o 'name="csrfmiddlewaretoken" value="[^"]*"' "$temp_dir/login.html" | sed 's/.*value="//; s/"$//' | head -n 1)"

    if [[ -z "$csrf_token" ]]; then
        echo "failed to extract CSRF token from the login page" >&2
        exit 1
    fi

    curl -k -sS -b "$temp_dir/cookies.txt" \
        -c "$temp_dir/cookies.txt" \
        -e "$service_base_url/accounts/login/?next=/" \
        -X POST "$service_base_url/accounts/login/?next=/" \
        --data-urlencode "csrfmiddlewaretoken=$csrf_token" \
        --data-urlencode 'username=admin' \
        --data-urlencode 'password=admin1234' \
        --data-urlencode 'next=/' >"$temp_dir/post_login_headers.txt"

    curl -k -sS -b "$temp_dir/cookies.txt" \
        "$service_base_url/" >"$temp_dir/home.html"

    if ! grep -Eq 'Signed in successfully\.|Sign out' "$temp_dir/home.html"; then
        echo "admin login verification failed for $service_base_url" >&2
        exit 1
    fi

    rm -rf "$temp_dir"
    trap - RETURN
}

main() {
    require_command curl
    require_command docker
    require_command openssl
    require_command unzip

    if [[ ! -f "$bundle_zip" ]]; then
        echo "deployment bundle ZIP not found: $bundle_zip" >&2
        exit 1
    fi

    echo "staging deployment bundle from $bundle_zip"
    stage_bundle

    echo "writing deployment overrides in $deployment_dir"
    write_env_file "$(random_hex 32)" "$(random_hex 24)" "$(random_hex 24)"
    write_override_file
    write_management_script

    echo "pulling published images"
    compose pull

    echo "resetting any existing stack state"
    compose down -v >/dev/null 2>&1 || true

    echo "starting production test stack"
    compose up -d

    echo "verifying management bootstrap completion"
    verify_management_completion

    echo "checking service status"
    compose ps

    echo "verifying HTTPS entrypoint on $service_base_url"
    verify_https_redirect

    echo "verifying admin login"
    verify_admin_login

    echo "production test instance is ready at $service_base_url"
    echo "deployment directory: $deployment_dir"
    echo "admin credentials: admin / admin1234"
}

main "$@"